apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "my-first-keptn-project"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "sequence1"
          triggeredOn:
            - event: "dev.sequence2.finished"
              selector:
                match:
                  evaluation.result: "fail"
          tasks: 
            - name: "saygoodbye"
        - name: "sequence2"
          tasks:
            - name: "sayhello"
