apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "my-first-keptn-project"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "sequence1"
          tasks: 
            - name: "saygoodbye"
        - name: "sequence2"
          tasks:
            - name: "sayhello"
        - name: "sequence3"
          triggeredOn:
            - event: "dev.sequence2.finished"
                selector:
                  match:
                    result: failed
          tasks: 
            - name: "saysequence3"
        - name: "sequence4"
          triggeredOn:
            - event: "dev.sequence2.finished"
                selector:
                  match:
                    result: success
          tasks: 
            - name: "saysequence4"
