apiVersion: spec.keptn.sh/0.2.3
kind: "Shipyard"
metadata:
  name: "my-first-keptn-project"
spec:
  stages:
    - name: "dev"
      sequences:
        - name: "sequence2"
          tasks:
            - name: "sayhello"
            - name: "evaluation"
              properties:
                timeframe: 15m
        - name: "sequence3"
          triggeredOn:
            - event: "dev.sequence2.finished"
          tasks: 
            - name: "saygoodbye"
