---
apiVersion: v2
actions:
  - name: "Run alpine image to say hello world"
    events:
      - name: "sh.keptn.event.sayhello.triggered"
    tasks:
      - name: "Shello"
        image: "ubuntu"
        files:
          - /job/shell/shello.sh
        cmd:
          - sh
        args:
          - "/keptn/job/shell/shello.sh"
  - name: "sequence3"
    events:
      - name: "sh.keptn.event.saygoodbye.triggered"
    tasks:
      - name: "Say Sequence 3"
        image: "alpine"
        cmd:
          - echo
        args:
          - 'Sequence 3 Webhook'
