---
apiVersion: v2
actions:
  - name: "Run alpine image to say hello world"
    events:
      - name: "sh.keptn.event.sayhello.triggered"
    tasks:
      - name: "Say Hello World"
        image: "alpine"
        cmd:
          - echo
        args:
          - 'hello world'
      - name: "Say Hello World again"
        image: "alpine"
        cmd:
          - echo
        args:
          - 'hello world again'
      - name: "Say ubuntu"
        image: "ubuntu"
        cmd:
          - echo
        args:
          - 'hello ubuntu'
      - name: "Shello"
        image: "ubuntu"
        files:
          - /job/shell/shello.sh
        cmd:
          - chmod
        args:
          - 755
          - /keptn/job/shell/shello.sh
          - &
          - sh
          - /keptn/job/shell/shello.sh
