---
apiVersion: v2
actions:
  - name: "Run alpine image to say hello world"
    events:
      - name: "sh.keptn.event.sayhello.triggered"
    tasks:
      - name: "Shello"
        image: "ubuntu"
        files:
          - /job/shell/shello.sh
        cmd:
          - sh
        args:
          - "/keptn/job/shell/shello.sh"          
